theme: jekyll-theme-cayman

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url:  http://cyf-yp.github.io
root: /yfc_essays/
permalink: :year/:month/:day/:title/
permalink_defaults:
